FROM eclipse-temurin:21-jdk as builder
ADD /build/libs/tutorial-webflux-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 10080
ENV JAVA_OPTS=""
#ENTRYPOINT ["java" $JAVA_OPT, "-jar", "/app.jar"]
ENTRYPOINT java $JAVA_OPTS -jar /app.jar